version: 2.1
orbs:
  node: circleci/node@5.0.2
  coveralls: coveralls/coveralls@2.2.5

jobs:
  build_and_test:
    docker:
      - image: cimg/node:18.20.7
      - image: postgres:14.20-trixie
        environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: test
    environment:
      DB_HOST: 127.0.0.1
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: test
      DATABASE_URL: postgresql://postgres:postgres@127.0.0.1:5432/test
      COVERALLS_REPO_TOKEN: mY2b1uEef1YzO5FpNjxm4DfCcRgeEcJGm
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          command: npx prisma generate
          name: Generate Prisma Client
      - run:
          command: npm run test:cov
          name: Run tests with coverage
      - coveralls/upload
workflows:
  build_test:
    jobs:
      - build_and_test
